nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%', 'http://192.168.88.29']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ["Origin","Access-Control-Allow-Origin","strict-origin-when-cross-origin","Accept","content-type", "Authorization","X-Auth-Token"]
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
